FarmerBrothers/FarmerBrothers/Controllers/ReopenWorkOrderController.cs
using FarmerBrothers.Data;
using FarmerBrothers.Models;
using FarmerBrothers.Utilities;
using System;
using System.Linq;
using System.Web.Mvc;

namespace FarmerBrothers.Controllers
{
    public class ReopenWorkOrderController : BaseController
    {
        // GET: ReopenWorkOrder
        public ActionResult ReopenWorkOrder()
        {
            return View();
        }

        public PartialViewResult WorkOrder(int id)
        {
            try
            {
                var workOrder = FarmerBrothersEntitites.WorkOrders.First(x => x.WorkorderID == id && x.WorkorderCallstatus != "Open");
                WorkOrderModel workOderModel = new WorkOrderModel() { CustomerID = workOrder.CustomerID, CustomerName = workOrder.CustomerName, CustomerState = workOrder.CustomerState, Notes = "" };
                return PartialView("WorkOrder", workOderModel);
            }
            catch (Exception)
            {
                return PartialView("WorkOrder", null);
            }
        }

        [HttpPost]
        public int ReOpenWorkOrder(int id, string notes)
        {
            try
            {
                var workOrder = FarmerBrothersEntitites.WorkOrders.First(x => x.WorkorderID == id);
                string oldworkOrderCallSatus = workOrder.WorkorderCallstatus;
                workOrder.WorkorderCallstatus = WorkOrderStatus.Open.ToString();
                workOrder.ClosedUserName = null;
                workOrder.WorkorderCloseUserid = null;
                workOrder.WorkorderCloseDate = null;
                workOrder.WorkorderClosureConfirmationNo = null;
                workOrder.NoServiceRequired = null;
                if (workOrder.WorkorderDetails != null)
                {
                    if (workOrder.WorkorderDetails.Count > 0)
                    {
                        WorkorderDetail workorderDetail = workOrder.WorkorderDetails.ElementAt(0);
                        if (workorderDetail != null)
                        {
                            workorderDetail.StartDateTime = null;
                            workorderDetail.InvoiceNo = null;
                            workorderDetail.ArrivalDateTime = null;
                            workorderDetail.CompletionDateTime = null;
                            workorderDetail.SpecialClosure = string.Empty;
                            workorderDetail.PhoneSolveid = null;
                        }
                    }
                }

                if (workOrder.WorkorderSchedules != null)
                {
                    foreach (var schedule in workOrder.WorkorderSchedules.ToList())
                    {
                        FarmerBrothersEntitites.WorkorderSchedules.Remove(schedule);
                    }
                }

                if (workOrder.WorkorderEquipments != null)
                {
                    foreach (var equipments in workOrder.WorkorderEquipments.ToList())
                    {
                        FarmerBrothersEntitites.WorkorderEquipments.Remove(equipments);
                    }
                }

                if (workOrder.WorkorderCalltypeid == 1600)
                {
                    if (workOrder.WorkorderInstallationSurveys != null)
                    {
                        foreach (var equipments in workOrder.WorkorderInstallationSurveys.ToList())
                        {
                            FarmerBrothersEntitites.WorkorderInstallationSurveys.Remove(equipments);
                        }
                    }
                }

                DateTime currentTime = Utility.GetCurrentTime(workOrder.CustomerZipCode, FarmerBrothersEntitites);
                NotesHistory noteHistory = new NotesHistory();
                noteHistory.WorkorderID = id;                
                noteHistory.Userid = System.Web.HttpContext.Current.Session["UserId"] != null ? Convert.ToInt32(System.Web.HttpContext.Current.Session["UserId"]) : 1234; 
                noteHistory.UserName = UserName;
                noteHistory.Notes = notes;
                noteHistory.AutomaticNotes = 0;
                noteHistory.EntryDate = currentTime;
                noteHistory.isDispatchNotes = 1;
                FarmerBrothersEntitites.NotesHistories.Add(noteHistory);



                NotesHistory noteHistory1 = new NotesHistory();
                noteHistory1.WorkorderID = id;
                noteHistory.Userid = System.Web.HttpContext.Current.Session["UserId"] != null ? Convert.ToInt32(System.Web.HttpContext.Current.Session["UserId"]) : 1234; 
                noteHistory1.UserName = UserName;
                noteHistory1.Notes = "Moved from " + oldworkOrderCallSatus + " to Open (Reopen)";
                noteHistory1.AutomaticNotes = 1;
                noteHistory1.EntryDate = currentTime;
                noteHistory1.isDispatchNotes = 1;
                FarmerBrothersEntitites.NotesHistories.Add(noteHistory1);

                WorkorderController wc = new WorkorderController();
                wc.UpdateWOModifiedElapsedTime(workOrder.WorkorderID);

                FarmerBrothersEntitites.SaveChanges();
                return 1;
            }
            catch (Exception)
            {
                return 0;
            }
        }

        public enum WorkOrderStatus
        {
            Accepted,
            Open
        }

    }
}

FarmerBrothers/FarmerBrothers/Controllers/WorkorderController.cs
using FarmerBrothers.Data;
using FarmerBrothers.Models;
using FarmerBrothers.Utilities;
using FarmerBrothersMailResponse.Controllers;
using LinqKit;
using Syncfusion.EJ.Export;
using Syncfusion.HtmlConverter;
using Syncfusion.JavaScript.Models;
using Syncfusion.Pdf;
using Syncfusion.XlsIO;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Customer = FarmerBrothers.Data.Contact;

namespace FarmerBrothers.Controllers
{
    public enum MailType
    {
        INFO,
        DISPATCH,
        REDIRECTED,
        SPAWN,
        SALESNOTIFICATION
    }

    public class WorkorderController : BaseController
    {

        int defaultFollowUpCall;

        public WorkorderController()
        {
            AllFBStatu FarmarBortherStatus = FarmerBrothersEntitites.AllFBStatus.Where(a => a.FBStatus == "None" && a.StatusFor == "Follow Up Call").FirstOrDefault();
            if (FarmarBortherStatus != null)
            {
                defaultFollowUpCall = FarmarBortherStatus.FBStatusID;
            }
        }

        #region load workorder view

        [HttpGet]
        public ActionResult WorkorderManagement(int? customerId, int? workOrderId, bool isNewPartsOrder = false, bool showAllTechs = false, bool isCustomerDashboard = false, bool isFromProcessCardScreen = false)
        {
            WorkorderManagementModel workOrderManagementModel = null;
            try
            {
                workOrderManagementModel = ConstructWorkorderManagementModel(customerId, workOrderId, isNewPartsOrder, showAllTechs, isCustomerDashboard, isFromProcessCardScreen);

            }
            catch (Exception ex)
            {
                int tmpCustomerId = Convert.ToInt32(customerId);
                string DBCustomerZipCode = FarmerBrothersEntitites.Contacts.Where(c => c.ContactID == tmpCustomerId).Select(id => id.PostalCode).FirstOrDefault();

                var zip = FarmerBrothersEntitites.Zips.Where(z => z.ZIP1 == DBCustomerZipCode).FirstOrDefault();
                if (zip == null)
                {
                    return View("InvalidZipCodeError");
                }
                else
                {
                    return View("Error");
                }

            }
            return View(workOrderManagementModel);
        }


        public ActionResult WorkorderPdf(int? WorkorderID)
        {
            WorkOrderPdfModel objDisplayPdf = new Models.WorkOrderPdfModel();

            objDisplayPdf.objWorkOrder = FarmerBrothersEntitites.WorkOrders.Where(w => w.WorkorderID == WorkorderID).FirstOrDefault();
            objDisplayPdf.objWorkorderSchedule = FarmerBrothersEntitites.WorkorderSchedules.Where(w => w.WorkorderID == WorkorderID && w.AssignedStatus != "Redirected" && w.AssignedStatus != "Declined").FirstOrDefault();
            objDisplayPdf.Invoice = FarmerBrothersEntitites.Invoices.Where(w => w.InvoiceUniqueid == FarmerBrothersEntitites.Invoices.Where(i => i.WorkorderID == WorkorderID).FirstOrDefault().InvoiceUniqueid).FirstOrDefault();

            WorkorderDetail workOrderDetail = FarmerBrothersEntitites.WorkorderDetails.Where(w => w.WorkorderID == WorkorderID).FirstOrDefault();
            if (workOrderDetail != null)
            {
                objDisplayPdf.CustomerSign = workOrderDetail.CustomerSignatureDetails;
                objDisplayPdf.TechnicianSign = workOrderDetail.TechnicianSignatureDetails;
                objDisplayPdf.CustomerSignatureBy = workOrderDetail.CustomerSignatureBy;
            }

            var getTechId = FarmerBrothersEntitites.WorkorderDetails.Where(w => w.WorkorderID == WorkorderID).FirstOrDefault();

            objDisplayPdf.Equipmentlist = (from WorkEquipment in FarmerBrothersEntitites.WorkorderEquipments
                                           join WorkType in FarmerBrothersEntitites.WorkorderTypes
                                           on WorkEquipment.CallTypeid equals WorkType.CallTypeID into temp1
                                           from we in temp1.DefaultIfEmpty()
                                           where WorkEquipment.WorkorderID == WorkorderID
                                           select new WorkorderEquipmentDetailModel()
                                           {
                                               Assetid = WorkEquipment.Assetid,
                                               WorkOrderType = we.Description,
                                               Temperature = WorkEquipment.Temperature,
                                               Weight = WorkEquipment.Weight,
                                               Ratio = WorkEquipment.Ratio,
                                               WorkPerformedCounter = WorkEquipment.WorkPerformedCounter,
                                               WorkDescription = WorkEquipment.WorkDescription,
                                               Category = WorkEquipment.Category,
                                               Manufacturer = WorkEquipment.Manufacturer,
                                               Model = WorkEquipment.Model,
                                               Location = WorkEquipment.Location,
                                               SerialNumber = WorkEquipment.SerialNumber,
                                               QualityIssue = WorkEquipment.QualityIssue,
                                               Email = WorkEquipment.Email
                                           }).ToList();

            IList<WorkOrderPartModel> Parts;

            foreach (var item in objDisplayPdf.Equipmentlist)
            {
                Parts = new List<WorkOrderPartModel>();
                IQueryable<WorkorderPart> workOrderParts = FarmerBrothersEntitites.WorkorderParts.Where(wp => wp.AssetID == item.Assetid);
                foreach (WorkorderPart workOrderPart in workOrderParts)
                {
                    WorkOrderPartModel workOrderPartModel = new WorkOrderPartModel(workOrderPart);
                    Parts.Add(workOrderPartModel);
                }

                item.Parts = Parts;
            }

            var workorderPdfId = objDisplayPdf.objWorkOrder.WorkorderID;
            string value = this.RenderRazorViewToString("~/Views/Workorder/WorkorderPdf.cshtml", objDisplayPdf).ToString();

            string baseURL = Server.MapPath("~/Views/Workorder/");

            // Html to PDF rendering using Webkit.
            HtmlToPdfConverter htmlConverter = new HtmlToPdfConverter(HtmlRenderingEngine.WebKit);
            WebKitConverterSettings webKitSettings = new WebKitConverterSettings();
            webKitSettings.WebKitPath = Server.MapPath("~/Content/QtBinaries");
            webKitSettings.PdfPageSize = PdfPageSize.A4;
            webKitSettings.EnableJavaScript = true;
            webKitSettings.EnableHyperLink = false;
            htmlConverter.ConverterSettings = webKitSettings;

            PdfDocument pdfDoc = htmlConverter.Convert(value, Server.MapPath("~/Content/"));
            pdfDoc.PageSettings.Size = PdfPageSize.A4;
            pdfDoc.Save("WorkorderFor_" + workorderPdfId + ".pdf", HttpContext.ApplicationInstance.Response, HttpReadType.Save);

            return View(objDisplayPdf);
        }

        public ActionResult WorkorderPdfData(int? WorkorderID)
        {
            WorkOrderPdfModel objDisplayPdf = new Models.WorkOrderPdfModel();

            objDisplayPdf.objWorkOrder = FarmerBrothersEntitites.WorkOrders.Where(w => w.WorkorderID == WorkorderID).FirstOrDefault();
            objDisplayPdf.objWorkorderSchedule = FarmerBrothersEntitites.WorkorderSchedules.Where(w => w.WorkorderID == WorkorderID && w.AssignedStatus != "Redirected" && w.AssignedStatus != "Declined").FirstOrDefault();
            objDisplayPdf.Invoice = FarmerBrothersEntitites.Invoices.Where(w => w.InvoiceUniqueid == FarmerBrothersEntitites.Invoices.Where(i => i.WorkorderID == WorkorderID).FirstOrDefault().InvoiceUniqueid).FirstOrDefault();

            WorkorderDetail workOrderDetail = FarmerBrothersEntitites.WorkorderDetails.Where(w => w.WorkorderID == WorkorderID).FirstOrDefault();
            if (workOrderDetail != null)
            {
                objDisplayPdf.CustomerSign = workOrderDetail.CustomerSignatureDetails;
                objDisplayPdf.TechnicianSign = workOrderDetail.TechnicianSignatureDetails;
                objDisplayPdf.CustomerSignatureBy = workOrderDetail.CustomerSignatureBy;
            }

            Contact contact = FarmerBrothersEntitites.Contacts.Where(c => c.ContactID == objDisplayPdf.objWorkOrder.CustomerID).FirstOrDefault();

            objDisplayPdf.Route = contact == null ? "" : contact.Route;

            objDisplayPdf.objWorkorderDetails = FarmerBrothersEntitites.WorkorderDetails.Where(w => w.WorkorderID == WorkorderID).FirstOrDefault();
            //FarmerBrothersEntitites.WorkorderDetails.Where(wr => wr.WorkorderID == workOrderId).Select(w => w.CustomerSignatureDetails).FirstOrDefault();

            objDisplayPdf.EquipmentRequestedlist = (from WorkEquipment in FarmerBrothersEntitites.WorkorderEquipmentRequesteds
                                                    join WorkType in FarmerBrothersEntitites.WorkorderTypes
                                                    on WorkEquipment.CallTypeid equals WorkType.CallTypeID into temp1
                                                    from we in temp1.DefaultIfEmpty()
                                                    join Symptom in FarmerBrothersEntitites.Symptoms

FarmerBrothers/FarmerBrothers/Views/ReopenWorkOrder/ReopenWorkOrder.cshtml
<link href="~/Content/Tpcm.css" rel="stylesheet" />
@{
    ViewBag.Title = "Reopen Work Order";
}
<script type="text/javascript">

    $( document ).ready( function ()
    {
        $( '#ReportLink' ).css( "color", "white" );
    } );
</script>
<form>
    <section class="container-fluid white-bg pad">
        <div class="row top-info">
            <div class="col-md-11">
                <b>Reopen Work Order</b>
            </div>
            @if (Request.QueryString["IsFromReports"] != null && Convert.ToBoolean(Request.QueryString["IsFromReports"]))
            {
                <div class="col-md-1">
                    @Html.ActionLink("Back", "AllReports", "Reports", new { @IsBack = 1 }, new { @Class = "btn btn-primary" })
                </div>
            }

        </div>
    </section>
    <section class="well">
        <div>
            <label style="width:120px;">Work Order ID:</label>
            <input type="text" pattern="\d*" class="numbersOnly" id="txtWorkOrderid" />
            <button type="button" class="btn btn-primary" id="btnSearch">Search</button>
            <label style="width:250px;"></label>
            <div></div>
            <br /><br />
            <div class="form-group" id="dvWorkOrder"></div>
        </div>
    </section>
</form>

<script type="text/javascript">
    $( function ()
    {

        jQuery( '.numbersOnly' ).keyup( function ()
        {
            this.value = this.value.replace( /[^0-9\.]/g, '' );
        } );

        $( "#btnSearch" ).click( function ()
        {
            if ( $( "#txtWorkOrderid" ).val().trim().length == 0 )
            {
                AlertPopup( "|Please enter work order id to reopen" );
            }
            else
            {
                var myUrl = '@Url.Action("WorkOrder", "ReopenWorkOrder")' + "?id=" + $( "#txtWorkOrderid" ).val();
                $.post( myUrl, function ( data )
                {
                    $( "#dvWorkOrder" ).html( data );
                    if ( $( "#dvWorkOrder div.test" ).length == 0 )
                    {
                        AlertPopup( "|No Work Order found or Work Order is in Open Status." );
                    }
                } );
            }
        } );
    } );
</script>

FarmerBrothers/FarmerBrothers/Views/ReopenWorkOrder/WorkOrder.cshtml
@model FarmerBrothers.Models.WorkOrderModel
@using FarmerBrothers.Models;
@if (Model != null)
{

    <form role="form">
        <div class="test" id="dvWorkorderList">
            <div>
                <label style="width:120px;">Customer ID:</label>
                @Html.DisplayFor(m => m.CustomerID, new { id = "txtCustomerID", name = "CustomerID" })
            </div>
            <div>
                <label style="width:120px;">Customer Name:</label>
                @Html.DisplayFor(m => m.CustomerName, new { id = "txtCustomerName", name = "CustomerName", @readonly = true })
            </div>
            <div>
                <label style="width:120px;">Customer State:</label>
                @Html.DisplayFor(m => m.CustomerState, new { id = "txtCustomerState", name = "CustomerState", @readonly = true })
            </div>
            <div>
                <label style="width:120px;">Reopen Notes:</label>
                @Html.TextAreaFor(m => m.Notes, new { id = "txtNotes", name = "notes", @cols = 35, @rows = 7 })
            </div>
            @{
    Dictionary<string, string> UserPrivilege = (Dictionary<string, string>)System.Web.HttpContext.Current.Session["UserPrivilege"+(int)System.Web.HttpContext.Current.Session["UserId"]] == null
                    ? Security.GetUserPrivilegeByUserId((int)System.Web.HttpContext.Current.Session["UserId"], null) :
                    (Dictionary<string, string>)System.Web.HttpContext.Current.Session["UserPrivilege"+(int)System.Web.HttpContext.Current.Session["UserId"]];
                if (UserPrivilege["Reopen Work Order"].ToLower() == Model.ACCESS_EDIT_ONLY || UserPrivilege["Reopen Work Order"].ToLower() == Model.ACCESS_FULL)
                {
                    <div style="align-items:center">
                        <button type="button" class="btn btn-primary" style="margin-left:290px;" id="btnSave">Reopen</button>
                    </div>
                }
            }

        </div>
    </form>
}
<script type="text/javascript">
    $( function ()
    {
        $( "#btnSave" ).click( function ()
        {
            var myUrl1 = '@Url.Action("ReopenWorkOrder", "ReopenWorkOrder")';
            if ( $( "#txtNotes" ).val().trim().length == 0 )
            {
                AlertPopup( "|Please enter reopen notes" );
                $( "#txtNotes" ).focus();
            }
            else
            {
                var dataToSend = { id: $( "#txtWorkOrderid" ).val(), notes: $( "#txtNotes" ).val() }
                $.ajax( {
                    type: 'POST',
                    url: myUrl1, // we are calling json method
                    dataType: 'json',
                    data: { id: $( "#txtWorkOrderid" ).val(), notes: $( "#txtNotes" ).val() },
                    success: function ( data )
                    {
                        AlertPopup( "|Work order " + $( "#txtWorkOrderid" ).val() + " successfully reopened." );
                        $( "#dvWorkOrder" ).html( "" );
                    },
                    error: function ( ex )
                    {
                        AlertPopup( "|Fail" );
                    }
                } );
                return false;
            }
        } );
    } );
</script>